export const ROUTES = {
  HOME: '/',
  PRICING: '/pricing',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  CONTACT_US: '/contact-us',
  TRANSLATE_DEMO: '/translate-demo',
  DASHBOARD: '/dashboard',
  BOOKS: '/books',
  BOOK_DETAILS: '/books/:bookId',
  RESERVATIONS: '/reservations',
  SEAT_BOOKING: '/seat-booking',
  PAYMENT: '/payment',
  COMMUNITY: '/community',
  EVENTS: '/events',
  PROFILE: '/profile',
  READING_PROGRESS: '/reading-progress',
  LEADERBOARD: '/leaderboard',
  REVIEWS: '/reviews',
  SETTINGS: '/settings',
  SUPPORT: '/support',
  ADMIN: '/admin',
  ADMIN_MEMBERS: '/admin/members',
  IT_HEAD: '/it-head',
  GUARDIAN: '/guardian',
} as const;
