export const ROUTES = {
  HOME: '/',
  REVIEWS_ALL: '/reviews-all',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  BOOKS: '/books',
  BOOK_DETAILS: '/books/:bookId',
  RESERVATIONS: '/reservations',
  SEAT_BOOKING: '/seat-booking',
  COMMUNITY: '/community',
  EVENTS: '/events',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  READING_PROGRESS: '/reading-progress',
  LEADERBOARD: '/leaderboard',
  REVIEWS: '/reviews',
  SETTINGS: '/settings',
  ADMIN: '/admin',
} as const;
